apiVersion: v1
kind: Service
metadata:
  name: {{ include "foodie.componentFullname" (dict "context" . "component" "frontend") }}
  namespace: {{ include "foodie.namespace" . }}
  labels:
    {{- include "foodie.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "foodie.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
