{{- if .Values.hpa.enabled }}
apiVersion: {{ .Values.hpa.apiVersion | default "autoscaling/v1" }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "foodie.componentFullname" (dict "context" . "component" "backend") }}
  namespace: {{ include "foodie.namespace" . }}
  labels:
    {{- include "foodie.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "foodie.componentFullname" (dict "context" . "component" "backend") }}
  minReplicas: {{ .Values.hpa.backend.minReplicas }}
  maxReplicas: {{ .Values.hpa.backend.maxReplicas }}
  {{- if eq (.Values.hpa.apiVersion | default "autoscaling/v1") "autoscaling/v2" }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.backend.targetCPUUtilizationPercentage }}
  {{- else }}
  targetCPUUtilizationPercentage: {{ .Values.hpa.backend.targetCPUUtilizationPercentage }}
  {{- end }}
{{- end }}
